# Generated by Django 4.1.3 on 2023-12-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('bio', models.CharField(max_length=55)),
                ('profile_image_url', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=55)),
                ('created_on', models.DateField()),
                ('active', models.IntegerField()),
                ('is_staff', models.BooleanField(max_length=55)),
                ('uid', models.CharField(max_length=55)),
            ],
        ),
    ]
