# Generated by Django 4.1.3 on 2023-12-14 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_category_post'),
        ('rareapi', '0002_remove_user_active_remove_user_is_staff'),
    ]

    operations = [
    ]
